version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0

executors:
  openjdk11:
    docker:
      - image: cimg/openjdk:11.0

workflows:
  test:
    jobs:
      - gradle/test:
          executor: openjdk11
          test_command: check
